### ISSUE TITLE
Example for habitat-lab

### ISSUE THREAD

**Issue by sai-prasanna** [Ending2015a/dungeon_maps#2]
Hi do you have an example of running this with habitat lab? I know that the API is generic enough to support it. But it would be helpful if you already have done it and I don't have to figure out the little details such as the camera axes etc in habitat.

**Comment by Ending2015a** [comment]
Hi @sai-prasanna 

You can find the full object-nav example in this repository: [Ending2015a/kemono-habitat-2022](https://github.com/Ending2015a/kemono-habitat-2022). And [this part of code](https://github.com/Ending2015a/kemono-habitat-2022/blob/3227d2b03f06d3c35e78aa9f4b652c2e6bb0b7de/Kemono/kemono/envs/wrap/map_builder.py#L332-L567) demonstrats how to use 'dungeon_maps' API with habitat sim observations to construct the semantic maps.

**Comment by sai-prasanna** [comment]
@Ending2015a Thanks! This is awesome!
