### ISSUE TITLE
problem under indoor-scene simulator

### ISSUE THREAD

**Issue by Heathcliff-saku** [Ending2015a/dungeon_maps#3]
Hi @Ending2015a, nice work! 
I encountered some issues while trying to project in an indoor-scene simulator: In the indoor setting, I wanted to generate a top-down map of the indoor environment. However, due to the ceiling's height covering the floor area, the parts that were supposed to be the floor in the height map possess the height of the ceiling. As a result, the generated top-down map marks all areas as walls, as shown in the figure below. Do you have any good suggestions? Is there support for removing the influence of ceilings in indoor environments?
![1](https://github.com/Ending2015a/dungeon_maps/assets/55010217/1ec6f25a-ee3d-44b4-a7a3-a81a98228e48)
![2](https://github.com/Ending2015a/dungeon_maps/assets/55010217/a4ac0ff2-f1b1-478b-928d-f9f45161371d)

**Comment by Ending2015a** [comment]
Hello @Heathcliff-saku , thanks for being interested in this project.
If you know the actual height of the ceiling, you can set the `trunc_height_max` defined in [here](https://github.com/Ending2015a/dungeon_maps/blob/master/dungeon_maps/maps.py#L145) when doing the projection. This will exclude any parts with a height greater than this value.

**Comment by Heathcliff-saku** [comment]
@Ending2015a Thank you for your timely response!  I tried setting trunc_height_max, and it worked very well!  I'll close this issue.
